### ISSUE TITLE
Negative Values Not Being Shown

### ISSUE THREAD

**Issue by gk7279** [venyao/shinyCircos#1]
Hi,

I was using the example-bar-plot-color.csv file with your demo web URL.

For some reasons, the negative values are not being shown on the plot. I did even try to adjust the Y co-ords of baselines, but still no luck.

Can you please comment on what I am missing?

Thanks

**Comment by gk7279** [comment]
Never mind. I figured it out. If the plot has to show both positive and negative values, then there shouldn't be any color column in the data file. Thanks.

**Comment by venyao** [comment]
Yes. You're right. In the latest version, if data with a color column was given to shinyCircos to make bidirectional bar plot, error info would be printed on the screen.
