### ISSUE TITLE
ERROR: dependency 'fastmap' is not available for package 'shiny'

### ISSUE THREAD

**Issue by wuxiaopei0509** [venyao/shinyCircos#10]
I cannot install the packages "shiny"  because there is no fastmap . And I cannot install fastmap .My R version is 3.3.3
Thank you

**Comment by venyao** [comment]
How do you install fastmap? With internet access, use the command install.packages(“fastmap”) in R console.
Please post more error information.

**Comment by wuxiaopei0509** [comment]
yeah,I use this command to install the package, but doesn't work. 
Thank you

**Comment by venyao** [comment]
What's the error message being printed in the R console when you were installing the fastmap package?

**Comment by wuxiaopei0509** [comment]
Thank you, venyao .I reinstall a different version R, and use Biomanager to install Bioconductor , then it work.

**Comment by venyao** [comment]
Glad to hear that. Please contact us without hesitation if you encounter any problem using shinyCircos.
