### ISSUE TITLE
Implement 'clear field' buttons for 'Data upload' tab

### ISSUE THREAD

**Issue by kemendle** [venyao/shinyCircos#2]
I am currently resetting the page in order to clear optional fields (such as 'Upload label data') that I have accidentally uploaded a file into. Is it possible to implement a button that will clear an optional field (or fields) so that I won't need to refresh the entire page if I make a mistake?

**Comment by venyao** [comment]
Dear kemendle,

You don't need to refresh the entire page even if your accidentally uploaded a file into the 'label data' field. You can tell shinyCircos to show or not show the label data using the 'Add labels' button in the 'Circos visualization' menu. 

We can add a 'clear field' button for 'Data upload' tab. However, this button can only clear the file name in the 'Data upload' tab. The uploaded data is still sent to the shinyCircos server and would be used by the server. This is a very common and frustrating problem with no real ideal solution. Please check this link (https://github.com/daattali/shinyjs/issues/104) for more information.

**Comment by kemendle** [comment]
Thank you, Wen! I will keep this in mind while using the application.
