### ISSUE TITLE
scripts how to generate input files

### ISSUE THREAD

**Issue by mictadlo** [venyao/shinyCircos#3]
Hi,
Do you have any scripts how to generate input files?

Thank you in advance

Michal

**Comment by mictadlo** [comment]
Hi Venyao,
I would like to create synteny plots between two assemblies. I assume I have to run BLASTN. Do you have any parameter recommendations? It would be great if you could show me a script to convert BLASTN output to the required format?

Thank you in advance,

Michal

**Comment by venyao** [comment]
You can use shinyCircos to create **links** between synteny regions of the two assemblies. Here is the format of input data for create links which contains 6 columns separated by commas or tabs.


```
chr1,start1,end1,chr2,start2,end2
chr20,37720821,47419255,chr5,162124929,168434522
chr8,76179361,83302661,chr1,162049212,213797379
chr2,38375277,49805216,chr11,19060895,36294068
```

For the BLASTN output,
(1) paste the output into a EXCEL sheet 
(2) delete the unneeded columns
(3) reorder the columns as the input file to create links mentioned above 
(4) save the EXCEL file as csv files which should be proper input files for shinyCircos

**Comment by mictadlo** [comment]
Hi, 
I have this file:

```
tig00007144,23113,30824,chr03,33203431,33211142
tig00007144,1,5564,chr03,33172892,33178421
tig00007144,30947,36357,chr03,33211132,33216579
tig00007144,36363,40867,chr03,33216622,33221153
tig00007144,18363,22411,chr03,33198553,33202624
tig00007144,7220,10393,chr03,33180129,33183315
tig00007144,14542,17807,chr03,33187551,33190858
tig00007144,11633,14556,chr03,33184564,33187523
tig00007144,16220,17919,chr03,33196726,33198473
tig00007144,14552,16012,chr03,33195009,33196462
```
but shinyCircos complains `Error: Data formatting error! Chromosome data should contain three (general type) or five columns (cytoband type). Please upload applicable chromosome data.`

What did I miss?

Thank you in advance,

Michal

**Comment by venyao** [comment]
Hi Michal，

You need two datasets. What you show in the previous post is the **links data** in correct format. The links data should be uploaded using the bottom left widget of the **Data upload** menu of shinyCircos. However, to create synteny plots, you still need another dataset which defines the lengths of all chromosomes. This dataset is the chromosome data which should be uploaded using the upper left widget of the **Data upload** menu of shinyCircos.

**Comment by venyao** [comment]
Hi Michal,

To get the output plot, you need to click the 'Go!' button first at the bottomleft of the 'Circos visualization' menu. Then you can download the PDF or SVG files using the three 'Download' button.

**Comment by mictadlo** [comment]
Now, I got `nrow of `region1` and `region2` differ.`. What did I miss?

**Comment by venyao** [comment]
Ok. Send me your data. venyao at qq.com
