### ISSUE TITLE
Warning: Error in ..stacktraceon..: object 'data.T' not found

### ISSUE THREAD

**Issue by jeffreyblanchard** [venyao/shinyCircos#7]
Hi, shinyCircos will be great for my research and teaching. The app opens in my browser (Firefox). I go to Circos visualization, select chromosome then click on Go and get the following error.

Warning: Error in ..stacktraceon..: object 'data.T' not found
45: isolate
44: <observer> [/home/jlb/Software/shinyCircos-master/server.R#290]
1: runApp

I am running Ubuntu 19.04 and R 3.5.2

**Comment by jeffreyblanchard** [comment]
Found a fix using require. This works

require(shinyjs)
require(shiny) 
library(shiny)
runApp("/home/jlb/Software/shinyCircos-master", launch.browser = TRUE)

**Comment by venyao** [comment]
Yes. You need to install the R packages required by shinyCircos to use it. Also remember to upload the input datasets prior to create the plot.
