### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by yize99** [venyao/shinyCircos#8]
Hi,
I run this App on http://150.109.59.144:3838/shinyCircos/ ,with the example data
After clicked the 'Download' button,  error as following,
Warning: Error in print: object 'figurecp' not found
  [No stack trace available]

**Comment by venyao** [comment]
I tested shinyCircos at http://150.109.59.144:3838/shinyCircos/ and can't replicate the issue you reported. Please make sure you are using shinyCircos with correct steps. Please click the "Go!" button in the "Circos visualization" menu after uploading your data using the "Data upload" menu. Then the circos plot will be generated in the web page under the "Circos visualization" menu. You can only download the figure after the plot was generated in the web page.
